### ISSUE TITLE
to-do list for all

### ISSUE THREAD

**Issue by itchyshin** [itchyshin/phylo_location_scale#4]
Here is a rough to-do list

- [x] Complete references @itchyshin 
- [x] Complete online materials 1: Model 3 @itchyshin 
- [x] Complete online materials 1: Model 4 @itchyshin 
- [x] Complete online materials 1: Model 5 @itchyshin 
- [x] Complete online materials 1: heritability + evolvability @itchyshin 
- [x] example figs @Ayumi-495 
- [x] other figs @Ayumi-495 + @szymekdr
